#!/usr/bin/env python3
"""Build gpt/nexo_gpt_writer.py: the Tower writer as ONE self-contained file.

ChatGPT's Python sandbox has no internet, so it cannot clone this repo. It fetches
this single file through its GitHub connector and runs it. The file embeds the
writer package (runtime/nexo_agent_api, no tests) and contracts/ as a zip.
Rebuild after any change to the writer: python scripts/build_gpt_writer_bundle.py
"""

from __future__ import annotations

import base64
import hashlib
import io
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "gpt" / "nexo_gpt_writer.py"

TEMPLATE = '''#!/usr/bin/env python3
"""NEXO Tower writer for ChatGPT (generated by scripts/build_gpt_writer_bundle.py - do not edit).

    python nexo_gpt_writer.py apply  TOWER.json PROPOSALS.json OUT.json
    python nexo_gpt_writer.py verify TOWER.json [EXPECTED_FINGERPRINT]

Bundle sha256: {digest}
"""
import base64, io, sys, tempfile, zipfile
from pathlib import Path

_BUNDLE = "{payload}"

_root = Path(tempfile.mkdtemp(prefix="nexo-gpt-writer-"))
zipfile.ZipFile(io.BytesIO(base64.b64decode(_BUNDLE))).extractall(_root)
sys.path.insert(0, str(_root))
from runtime.nexo_agent_api.gpt_writer import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


def build() -> Path:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("runtime/__init__.py", "")
        for package in ("nexo_agent_api", "nexo_execution", "portable_camb"):
            for path in sorted((REPO / "runtime" / package).glob("*")):
                if path.suffix in (".py", ".json") and (not path.name.startswith("test_") or path.name == "test_registry.py"):
                    archive.write(path, f"runtime/{package}/{path.name}")
        for path in sorted((REPO / "contracts").rglob("*.json")):
            archive.write(path, path.relative_to(REPO).as_posix())
    payload = base64.b64encode(buffer.getvalue()).decode("ascii")
    digest = hashlib.sha256(buffer.getvalue()).hexdigest()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(TEMPLATE.format(payload=payload, digest=digest), encoding="utf-8", newline="\n")
    return OUT


if __name__ == "__main__":
    out = build()
    print(out, out.stat().st_size)
