#!/usr/bin/env python3
"""Build gpt/nexo_gpt_writer.py: the Tower writer as ONE self-contained file.

ChatGPT's Python sandbox has no internet, so it cannot clone this repo. It fetches
this single file through its GitHub connector and runs it. The file embeds the
writer package (runtime/nexo_agent_api, no tests) and contracts/ as a zip.
Rebuild after any change to the writer: python scripts/build_gpt_writer_bundle.py
"""

from __future__ import annotations

import ast
import base64
import hashlib
import io
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "gpt" / "nexo_gpt_writer.py"

TEMPLATE = '''#!/usr/bin/env python3
"""NEXO Tower writer for ChatGPT (generated by scripts/build_gpt_writer_bundle.py - do not edit).

    python nexo_gpt_writer.py apply  TOWER.json PROPOSALS.json OUT.json
    python nexo_gpt_writer.py verify TOWER.json [EXPECTED_FINGERPRINT]
    python nexo_gpt_writer.py frontier TOWER.json [ROADMAP_ID]
    python nexo_gpt_writer.py handoff TOWER.json list ROLE
    python nexo_gpt_writer.py memory <context|search|dream|related|feedback> ...

Bundle sha256: {digest}
"""
import base64, io, sys, tempfile, zipfile
from pathlib import Path

_BUNDLE = "{payload}"

_root = Path(tempfile.mkdtemp(prefix="nexo-gpt-writer-"))
zipfile.ZipFile(io.BytesIO(base64.b64decode(_BUNDLE))).extractall(_root)
sys.path.insert(0, str(_root))
from runtime.nexo_agent_api.gpt_writer import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)

_MEMORY_LOADER = REPO / "gpt" / "nexo_memory.py"
_MEMORY_MEMBERS = (
    "runtime/nexo_agent_api/memory.py",
    "runtime/nexo_agent_api/memory_cli.py",
)


def _memory_sources() -> dict[str, bytes]:
    """Extract the reviewed memory runtime from the private-memory loader."""
    tree = ast.parse(_MEMORY_LOADER.read_text(encoding="utf-8"))
    payload = None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(isinstance(target, ast.Name) and target.id == "_BUNDLE" for target in node.targets):
            payload = ast.literal_eval(node.value)
            break
    if not isinstance(payload, str):
        raise RuntimeError("gpt/nexo_memory.py has no embedded _BUNDLE")
    with zipfile.ZipFile(io.BytesIO(base64.b64decode(payload))) as source:
        names = set(source.namelist())
        missing = [name for name in _MEMORY_MEMBERS if name not in names]
        if missing:
            raise RuntimeError("memory bundle missing: " + ", ".join(missing))
        return {name: source.read(name) for name in _MEMORY_MEMBERS}


def _write_deterministic(archive: zipfile.ZipFile, name: str, data: bytes) -> None:
    """Write a stable ZIP member: source mtimes must never change the Writer hash."""
    info = zipfile.ZipInfo(name, date_time=_ZIP_EPOCH)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.create_system = 3
    info.external_attr = 0o100644 << 16
    archive.writestr(info, data)


def build() -> Path:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        _write_deterministic(archive, "runtime/__init__.py", b"")
        for package in ("nexo_agent_api", "nexo_execution", "portable_camb"):
            package_root = REPO / "runtime" / package
            for path in sorted(package_root.rglob("*")):
                if path.is_file() and path.suffix in (".py", ".json") and (not path.name.startswith("test_") or path.name == "test_registry.py"):
                    rel = path.relative_to(package_root).as_posix()
                    _write_deterministic(archive, f"runtime/{package}/{rel}", path.read_bytes())
        archived = set(archive.namelist())
        for name, data in _memory_sources().items():
            if name not in archived:
                _write_deterministic(archive, name, data)
        for path in sorted((REPO / "contracts").rglob("*.json")):
            _write_deterministic(archive, path.relative_to(REPO).as_posix(), path.read_bytes())
    payload = base64.b64encode(buffer.getvalue()).decode("ascii")
    digest = hashlib.sha256(buffer.getvalue()).hexdigest()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(TEMPLATE.format(payload=payload, digest=digest), encoding="utf-8", newline="\n")
    return OUT

# User-owned file in Drive NEXO_INBOX/_runtime/ (service accounts cannot own files;
# they can update the content of a file the owner created).
DRIVE_BUNDLE_FILE_ID = "1DBw9H1wUHjZkasE2BI-aEafCzNnjKOjV"


def upload(path: Path) -> str:
    """Publish the bundle to Drive so ChatGPT gets it as a real file (file_uri).

    ChatGPT's GitHub connector shows file text but cannot hand it to the Python
    sandbox; the Drive connector can. Uses the writer service account.
    """
    import sys

    sys.path.insert(0, str(REPO))
    from runtime.nexo_agent_api.drive_transport import _UPLOAD, DriveInbox

    session = DriveInbox(write=True).session
    session.patch(f"{_UPLOAD}/{DRIVE_BUNDLE_FILE_ID}", params={"uploadType": "media", "supportsAllDrives": "true"},
                  data=path.read_bytes(), headers={"Content-Type": "text/plain"}, timeout=120).raise_for_status()
    return DRIVE_BUNDLE_FILE_ID


if __name__ == "__main__":
    import sys

    out = build()
    print(out, out.stat().st_size)
    if "--upload" in sys.argv:
        print("drive file id:", upload(out))
