#!/usr/bin/env python3
"""Build gpt/nexo_gpt_writer.py: the Tower writer as ONE self-contained file.

ChatGPT's Python sandbox has no internet, so it cannot clone this repo. It fetches
this single file through its GitHub connector and runs it. The file embeds the
writer package (runtime/nexo_agent_api, no tests) and contracts/ as a zip.
Rebuild after any change to the writer: python scripts/build_gpt_writer_bundle.py
"""

from __future__ import annotations

import base64
import hashlib
import io
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "gpt" / "nexo_gpt_writer.py"

TEMPLATE = '''#!/usr/bin/env python3
"""NEXO Tower writer for ChatGPT (generated by scripts/build_gpt_writer_bundle.py - do not edit).

    python nexo_gpt_writer.py apply  TOWER.json PROPOSALS.json OUT.json
    python nexo_gpt_writer.py verify TOWER.json [EXPECTED_FINGERPRINT]
    python nexo_gpt_writer.py frontier TOWER.json [ROADMAP_ID]
    python nexo_gpt_writer.py handoff TOWER.json list ROLE
    python nexo_gpt_writer.py memory <context|search|dream|related|feedback> ...
    python nexo_gpt_writer.py retrieval <sync|search|context|get|trace|groups|dream|diff|serve> ...
    python nexo_gpt_writer.py continuity <inspect|context|prepare> ...

Bundle sha256: {digest}
"""
import base64, io, sys, tempfile, zipfile
from pathlib import Path

_BUNDLE = "{payload}"

_root = Path(tempfile.mkdtemp(prefix="nexo-gpt-writer-"))
zipfile.ZipFile(io.BytesIO(base64.b64decode(_BUNDLE))).extractall(_root)
sys.path.insert(0, str(_root))
from runtime.nexo_agent_api.gpt_writer import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)

_REQUIRED_EXTENSION_SOURCES = (
    "memory.py", "memory_cli.py", "retrieval.py", "retrieval_cli.py",
    "retrieval_mcp.py", "retrieval_models.py",
    "continuity.py", "continuity_cli.py", "continuity_context.py", "enxame.py",
)

def _write_deterministic(archive: zipfile.ZipFile, name: str, data: bytes) -> None:
    """Write a stable ZIP member: source mtimes must never change the Writer hash."""
    info = zipfile.ZipInfo(name, date_time=_ZIP_EPOCH)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.create_system = 3
    info.external_attr = 0o100644 << 16
    archive.writestr(info, data)


def build() -> Path:
    # Missing extension sources must fail closed, never strip installed commands.
    for name in _REQUIRED_EXTENSION_SOURCES:
        path = REPO / "runtime" / "nexo_agent_api" / name
        if not path.is_file():
            raise RuntimeError(f"Writer extension source missing: {path.relative_to(REPO)}")
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        _write_deterministic(archive, "runtime/__init__.py", b"")
        for package in ("nexo_agent_api", "nexo_execution", "portable_camb"):
            package_root = REPO / "runtime" / package
            for path in sorted(package_root.rglob("*"), key=lambda path: path.relative_to(package_root).as_posix()):
                if path.is_file() and path.suffix in (".py", ".json") and (not path.name.startswith("test_") or path.name == "test_registry.py"):
                    rel = path.relative_to(package_root).as_posix()
                    _write_deterministic(archive, f"runtime/{package}/{rel}", path.read_bytes())
        contracts_root = REPO / "contracts"
        if contracts_root.is_dir():
            for path in sorted(contracts_root.rglob("*.json"), key=lambda path: path.relative_to(REPO).as_posix()):
                _write_deterministic(archive, path.relative_to(REPO).as_posix(), path.read_bytes())
    payload = base64.b64encode(buffer.getvalue()).decode("ascii")
    digest = hashlib.sha256(buffer.getvalue()).hexdigest()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(TEMPLATE.format(payload=payload, digest=digest), encoding="utf-8", newline="\n")
    return OUT

# User-owned file in Drive NEXO_INBOX/_runtime/ (service accounts cannot own files;
# they can update the content of a file the owner created).
DRIVE_BUNDLE_FILE_ID = "1DBw9H1wUHjZkasE2BI-aEafCzNnjKOjV"


def upload(path: Path) -> str:
    """Publish the bundle to Drive so ChatGPT gets it as a real file (file_uri).

    ChatGPT's GitHub connector shows file text but cannot hand it to the Python
    sandbox; the Drive connector can. Uses the writer service account.
    """
    import sys

    sys.path.insert(0, str(REPO))
    from runtime.nexo_agent_api.drive_transport import _UPLOAD, DriveInbox

    session = DriveInbox(write=True).session
    session.patch(f"{_UPLOAD}/{DRIVE_BUNDLE_FILE_ID}", params={"uploadType": "media", "supportsAllDrives": "true"},
                  data=path.read_bytes(), headers={"Content-Type": "text/plain"}, timeout=120).raise_for_status()
    return DRIVE_BUNDLE_FILE_ID


if __name__ == "__main__":
    import sys

    out = build()
    print(out, out.stat().st_size)
    if "--upload" in sys.argv:
        print("drive file id:", upload(out))
